### ISSUE TITLE
issue with number up to n limits in round vue filter.

### ISSUE THREAD

**Issue by divyanshu-lloyds** [rascada/vue-round-filter#1]
i think it's a bug when you use simple round, it works but if you are using with number like {{ round 3}} does not work.

**Comment by geekappsmx** [comment]
you can use 

`| round(2)`

**Comment by rascada** [comment]
I will provide update shortly and try to reproduce this bug

**Comment by mikermcneil** [comment]
I think this might be a Vue 2 thing.  I ended up with the same solution as @geekappsmx 👍 

btw @rascada, thanks for this!  I'm [including](https://github.com/mikermcneil/parasails/commit/ea39839a4c6e414e21014658add71e31a5a53748) your filter (with a couple of minor tweaks) in the next version of parasails (included by default in all new Sails apps using our "Web app" template)
